/**
 * Created by @VanSoftware on 2019-07-04.
 */

class Config{

    /**
     *
     * VIEW
     *
     */

    static REDUX_ACTION_VIEW_OVERLAY_TOGGLE = 'REDUX_ACTION_VIEW_OVERLAY_TOGGLE';
    static REDUX_ACTION_VIEW_OVERLAY_OPEN = 'REDUX_ACTION_VIEW_OVERLAY_OPEN';
    static REDUX_ACTION_VIEW_OVERLAY_CLOSE = 'REDUX_ACTION_VIEW_OVERLAY_CLOSE';
    static REDUX_ACTION_VIEW_OVERLAY_RESET = 'REDUX_ACTION_VIEW_OVERLAY_RESET';


    static REDUX_ACTION_VIEW_COVER_TOGGLE = 'REDUX_ACTION_VIEW_COVER_TOGGLE';
    static REDUX_ACTION_VIEW_COVER_OPEN = 'REDUX_ACTION_VIEW_COVER_OPEN';
    static REDUX_ACTION_VIEW_COVER_CLOSE = 'REDUX_ACTION_VIEW_COVER_CLOSE';
    static REDUX_ACTION_VIEW_COVER_RESET = 'REDUX_ACTION_VIEW_COVER_RESET';


    static REDUX_ACTION_VIEW_COMMON_DOCUMENT_BACKGROUND_SCROLL_ENABLE = 'REDUX_ACTION_VIEW_COMMON_DOCUMENT_BACKGROUND_SCROLL_ENABLE';
    static REDUX_ACTION_VIEW_COMMON_DOCUMENT_BACKGROUND_SCROLL_DISABLE = 'REDUX_ACTION_VIEW_COMMON_DOCUMENT_BACKGROUND_SCROLL_DISABLE';


    /**
     *
     * MODEL
     *
     */

    static REDUX_ACTION_MODEL_COVER_NETWORK_CHOOSE = 'REDUX_ACTION_MODEL_COVER_NETWORK_CHOOSE';


    /**
     *
     * CONTROLLER
     *
     */

    static REDUX_ACTION_CONTROLLER_COVER_NETWORK_CHOOSE = 'REDUX_ACTION_CONTROLLER_COVER_NETWORK_CHOOSE';
    static REDUX_ACTION_CONTROLLER_COVER_CLOSE = 'REDUX_ACTION_CONTROLLER_COVER_CLOSE';
}

export default Config;