export const redux = {
  SET: "store_SET",
  CHECK: "store_CHECK",

  AUTH_USER_SET: "store_AUTH_USER_SET",
  AUTH_TOKEN_SET: "store_AUTH_TOKEN_SET",

  COVER_OPEN: "store_COVER_OPEN",
  COVER_CLOSE: "store_COVER_CLOSE",
  COVER_TOGGLE: "store_COVER_TOGGLE",
  COVER_NETWORK_CLEAR: "store_COVER_NETWORK_CLEAR",
  COVER_NETWORK_SET: "store_COVER_NETWORK_SET",

  HISTORY_PUSH: "store_HISTORY_PUSH",
  HISTORY_POP: "store_HISTORY_POP",
  HISTORY_CLEAR: "store_HISTORY_CLEAR",

  NETWORKS_SET: "store_NETWORKS_SET",
  NETWORKS_SET_IS_LOADING: "store_NETWORKS_SET_IS_LOADING",
  NETWORKS_SET_IS_FETCHED: "store_NETWORKS_SET_IS_FETCHED",
  NETWORKS_SET_LIST: "store_NETWORKS_SET_LIST",
  NETWORKS_CLEAR_LIST: "store_NETWORKS_CLEAR_LIST",
  NETWORKS_PUSH_LIST: "store_NETWORKS_PUSH_LIST",

  ARTICLES_SET: "store_ARTICLES_SET",
  ARTICLES_SET_IS_LOADING: "store_ARTICLES_SET_IS_LOADING",
  ARTICLES_SET_IS_FETCHED: "store_ARTICLES_SET_IS_FETCHED",
  ARTICLES_SET_LIST: "store_ARTICLES_SET_LIST",
  ARTICLES_CLEAR_LIST: "store_ARTICLES_CLEAR_LIST",
  ARTICLES_PUSH_LIST: "store_ARTICLES_PUSH_LIST",

  RESOURCE_EXTERNAL_NETWORKS_SET: "store_RESOURCE_EXTERNAL_NETWORKS_SET",
  RESOURCE_EXTERNAL_NETWORKS_SET_IS_LOADING: "store_RESOURCE_EXTERNAL_NETWORKS_SET_IS_LOADING",
  RESOURCE_EXTERNAL_NETWORKS_SET_IS_FETCHED: "store_RESOURCE_EXTERNAL_NETWORKS_SET_IS_FETCHED",
  RESOURCE_EXTERNAL_NETWORKS_SET_LIST: "store_RESOURCE_EXTERNAL_NETWORKS_SET_LIST",

  RESOURCE_DEFAULT_SKILLS_SET: "store_RESOURCE_DEFAULT_SKILLS_SET",
  RESOURCE_DEFAULT_SKILLS_SET_IS_LOADING: "store_RESOURCE_DEFAULT_SKILLS_SET_IS_LOADING",
  RESOURCE_DEFAULT_SKILLS_SET_IS_FETCHED: "store_RESOURCE_DEFAULT_SKILLS_SET_IS_FETCHED",
  RESOURCE_DEFAULT_SKILLS_SET_LIST: "store_RESOURCE_DEFAULT_SKILLS_SET_LIST",

  RESOURCE_DEFAULT_CATEGORIES_SET: "store_RESOURCE_DEFAULT_CATEGORIES_SET",
  RESOURCE_DEFAULT_CATEGORIES_SET_IS_LOADING: "store_RESOURCE_DEFAULT_CATEGORIES_SET_IS_LOADING",
  RESOURCE_DEFAULT_CATEGORIES_SET_IS_FETCHED: "store_RESOURCE_DEFAULT_CATEGORIES_SET_IS_FETCHED",
  RESOURCE_DEFAULT_CATEGORIES_SET_LIST: "store_RESOURCE_DEFAULT_CATEGORIES_SET_LIST",

  MODAL_RESET: "store_MODAL_RESET",
  MODAL_OPEN: "store_MODAL_OPEN",
  MODAL_CLOSE: "store_MODAL_CLOSE",
  MODAL_REGISTER: "store_MODAL_REGISTER",
  MODAL_UNREGISTER: "store_MODAL_UNREGISTER",
};

export const sagas = {
  NETWORKS_LIST: "saga_NETWORKS_LIST",
  ARTICLES_LIST: "saga_ARTICLES_LIST",
  AUTH_UPDATE: "saga_AUTH_UPDATE",
};
